// <auto-generated />
using System;
using ConsultantsSalary.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsultantsSalary.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsultantsSalary.Domain.Entities.Consultant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Consultants");
                });

            modelBuilder.Entity("ConsultantsSalary.Domain.Entities.ConsultantTaskAssignment", b =>
                {
                    b.Property<Guid>("ConsultantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConsultantId", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("ConsultantTaskAssignments");
                });

            modelBuilder.Entity("ConsultantsSalary.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ConsultantsSalary.Domain.Entities.RoleRateHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RatePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "EffectiveDate");

                    b.ToTable("RoleRateHistories");
                });

            modelBuilder.Entity("ConsultantsSalary.Domain.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ConsultantsSalary.Domain.Entities.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsultantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateWorked")
                        .HasColumnType("date");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("RateSnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RateSnapshotId");

                    b.HasIndex("TaskId");

                    b.HasIndex("ConsultantId", "DateWorked");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("ConsultantsSalary.Domain.Entities.Consultant", b =>
                {
                    b.HasOne("ConsultantsSalary.Domain.Entities.Role", "Role")
                        .WithMany("Consultants")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ConsultantsSalary.Domain.Entities.ConsultantTaskAssignment", b =>
                {
                    b.HasOne("ConsultantsSalary.Domain.Entities.Consultant", "Consultant")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsultantsSalary.Domain.Entities.Task", "Task")
                        .WithMany("Assignments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ConsultantsSalary.Domain.Entities.RoleRateHistory", b =>
                {
                    b.HasOne("ConsultantsSalary.Domain.Entities.Role", "Role")
                        .WithMany("RateHistory")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ConsultantsSalary.Domain.Entities.TimeEntry", b =>
                {
                    b.HasOne("ConsultantsSalary.Domain.Entities.Consultant", "Consultant")
                        .WithMany("TimeEntries")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsultantsSalary.Domain.Entities.RoleRateHistory", "RateSnapshot")
                        .WithMany()
                        .HasForeignKey("RateSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConsultantsSalary.Domain.Entities.Task", "Task")
                        .WithMany("TimeEntries")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("RateSnapshot");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ConsultantsSalary.Domain.Entities.Consultant", b =>
                {
                    b.Navigation("TaskAssignments");

                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("ConsultantsSalary.Domain.Entities.Role", b =>
                {
                    b.Navigation("Consultants");

                    b.Navigation("RateHistory");
                });

            modelBuilder.Entity("ConsultantsSalary.Domain.Entities.Task", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
